### ISSUE TITLE
concat discriminator forward error

### ISSUE THREAD

**Issue by crcrpar** [crcrpar/pytorch.sngan_projection#4]
```
Traceback (most recent call last):
  File "train_64.py", line 402, in <module>
    main()
  File "train_64.py", line 325, in main
    dis_fake = dis(fake, pseudo_y)
  File "/home/crcrpar/.pyenv/versions/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/crcrpar/.ghq/github.com/crcrpar/pytorch.sngan_projection/models/discriminators/snresnet64.py", line 91, in forward
    h = self.block1(h)
  File "/home/crcrpar/.pyenv/versions/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/crcrpar/.ghq/github.com/crcrpar/pytorch.sngan_projection/models/discriminators/resblocks.py", line 72, in forward
    return self.shortcut(x) + self.residual(x)
  File "/home/crcrpar/.ghq/github.com/crcrpar/pytorch.sngan_projection/models/discriminators/resblocks.py", line 75, in shortcut
    return self.c_sc(F.avg_pool2d(x, 2))
  File "/home/crcrpar/.pyenv/versions/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/crcrpar/.pyenv/versions/env1/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 1, 1], expected input[64, 256, 4, 4] to have 3 channels, but got 256 channels instead
```

**Comment by crcrpar** [comment]
Solved
